import '../styles/main.css'

export const metadata = {
  title: 'LEVEL',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="ru">
      <body>{children}</body>
    </html>
  )
}


export default RootLayout